### ISSUE TITLE
remove book, post min_lengh limit

### ISSUE THREAD

**Issue by djgnfj-svg** [djgnfj-svg/Resee_project#6]
book이나 post를 만들때 limit을 없애준다

작성해주시는데 왜 막냐 내비두자

book max도 구지 막지마라

**Comment by b-hyoung** [comment]
최소글자 1글자로 막아둠

**Comment by djgnfj-svg** [comment]
그냥 막지말라니까 왜 1글자로 막음? 그냥 비워도 되게 하자
